apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intelligent-optimizer-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: intelligent-cluster-optimizer
    newName: intelligent-cluster-optimizer
    newTag: latest

commonLabels:
  app.kubernetes.io/part-of: intelligent-cluster-optimizer
  app.kubernetes.io/managed-by: kustomize
